### ISSUE TITLE
Only one sensor is created when installing BoM

### ISSUE THREAD

**Issue by JimboJamez** [AdamGit69/AFDR#1]
Hey Adam

I am trying to get this up and running in my HA but when I installed the BoM integration only '**_sensor.clyde_north_fire_danger_0_**' was created. Now when I update the yaml with the correct sensor name I am getting the following error in the logs, and nothing is displayed in the card:

> Logger: homeassistant.helpers.event
Source: helpers/template.py:569
First occurred: 3:35:11 PM (29 occurrences)
Last logged: 3:40:34 PM

> Error while processing template: Template<template=(<center> <img src='/local/moderate.png' width='50%'> Today's **FDR** for your home location is <font color = green> **MODERATE** </font> Tomorrow, {{ as_timestamp(states.sensor.clyde_north_fire_danger_1.attributes.date) | timestamp_custom('%A') }}, the forecast FDR is {{ states('sensor.clyde_north_fire_danger_1') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_2.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_2') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_3.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_3') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_4.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_4') }} </center>) renders=22>
Error while processing template: Template<template=(<center> <ha-alert alert-type="error"> ALERT - Current BOM Warnings = 2<BR> {{ state_attr("sensor.clyde_north_warnings" , "warnings") [0].short_title }}<BR> {{ state_attr("sensor.clyde_north_warnings" , "warnings") [1].short_title }}<BR> </ha-alert> </center>) renders=24>
Error while processing template: Template<template=(<center> <img src='/local/moderate.png' width='50%'> Today's **FDR** for your home location is <font color = green> **MODERATE** </font> Tomorrow, {{ as_timestamp(states.sensor.clyde_north_fire_danger_1.attributes.date) | timestamp_custom('%A') }}, the forecast FDR is {{ states('sensor.clyde_north_fire_danger_1') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_2.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_2') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_3.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_3') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_4.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_4') }} </center>) renders=26>
Error while processing template: Template<template=(<center> <ha-alert alert-type="error"> ALERT - Current BOM Warnings = 2<BR> {{ state_attr("sensor.clyde_north_warnings" , "warnings") [0].short_title }}<BR> {{ state_attr("sensor.clyde_north_warnings" , "warnings") [1].short_title }}<BR> </ha-alert> </center>) renders=28>
Error while processing template: Template<template=(<center> <img src='/local/moderate.png' width='50%'> Today's **FDR** for your home location is <font color = green> **MODERATE** </font> Tomorrow, {{ as_timestamp(states.sensor.clyde_north_fire_danger_1.attributes.date) | timestamp_custom('%A') }}, the forecast FDR is {{ states('sensor.clyde_north_fire_danger_1') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_2.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_2') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_3.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_3') }} {{ as_timestamp(states.sensor.clyde_north_fire_danger_4.attributes.date) | timestamp_custom('%A') }}'s FDR is forecast as {{ states('sensor.clyde_north_fire_danger_4') }} </center>) renders=30>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 567, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2305, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 4, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: list object has no element 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 693, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: list object has no element 1

Do you have any idea how i can resolve this?

**Comment by JimboJamez** [comment]
resolved by reinstalling the BoM integration. Thanks
